config/routes.rb
Rails.application.routes.draw do

  ALL_REST_ACTION = [:index, :new, :create, :show, :edit, :update, :destroy ]
  resources :addresses, param: :address_id, only: [:create, :update, :destroy ] do

  end

  resources :campuses, param: :campus_id, only: [:show, :index] do
    member do
      resources :stores,param: :store_id, only: [:index]
    end
  end

  resources :orders, param: :order_id, only: [:show, :index, :create, :show, :update] do
    member do
      # 获取订单的支付chagre
      get :get_charge_for_unpaid_order
    end

    collection do
      # get :test_print
    end
  end

  resources :users, param: :user_id, only: [:index] do
    collection do
      # 验证码登录
      post :login_with_sms_code

      # 绑定微信
      post :bind_weixin
    end

    member do
      resources :coupons, only: [:index]
    end
  end

  resources :services ,except: ALL_REST_ACTION do
    collection do
      get :get_image_form

      # 发送登录验证码
      post :send_login_sms_code

      # 基础设置
      get :basic_config

      # pingpp支付回调
      post :pingpp_pay_done

      # pingpp支付回调
      get :pingpp_pay_done

      # 随机推荐店铺
      get :random_recommend_store_in_campus

      # pingpp livemode支付回调
      post :pingpp_pay_done_for_alive

      # pingpp livemode支付回调
      get :pingpp_pay_done_for_alive

      # 搜索学校内的店铺和商品
      get :search_product_and_store_for_campus

      get :download

      # 更新检查
      get :check_update
    end
  end

  resources :stores, param: :store_id, only: [:show]

  resources :products, param: :product_id, only: [:show]

  resources :authorizations do
    collection do
      # 微信登录
      post :authorization

      # 微信公众号开发验证
      get :weixin

      # 微信
      #get :redirect_weixin

      # 获取红包入口
      get :get_coupon
    end
  end

  resources :announcements, only: [:index]

  # 管理者路由部分
  namespace :management do
    # 管理者查看订单API接口
    namespace :api do
      namespace :v1 do

        # 管理者
        resources :managers, only: [:index] do
          collection do


            # 发送验证码
            get :send_login_code

            # 用验证码登录
            get :login_with_sms_code
          end
        end

        # 订单查询
        resources :orders, only: [:index, :update]

      end
    end

    devise_for :managers, controllers: {sessions: 'management/devise/sessions', registrations: 'management/devise/registrations'}

    resources :managers, only: [:show]
    resources :orders, only: [:index]
    resources :statistics, only: [:index]

    # 店铺管理
    resources :stores, only: [:index, :show, :update, :new, :create] do

      # 店铺商品管理
      resources :products

    end
  end

  # 送餐员路由部分
  namespace :expresses do
    namespace :api do
      namespace :v1 do

        # 管理者
        resources :expressers, except: ALL_REST_ACTION do
          collection do
            # 送餐员登录
            post :sign_in

            # 送餐员扫二维码邦订单
            post :bind_order
          end
        end

        # 订单查询
        resources :orders, only: [:index]

      end
    end
  end

  # 移动端
    namespace :mobile do
      namespace :v1 do

        # 管理者
        resources :campuses
      end
    end

end

app/models/concerns/management/api/v1/order_concern.rb
# encoding: utf-8

module Concerns::Management::Api::V1::OrderConcern

  extend ActiveSupport::Concern

  included do
    # 通用查询方法
    include Concerns::Query::Methods
  end

  module ClassMethods

    # 管理者查询该学校的订单
    #
    # @param options [Hash]
    # @option options [Manager] :manager 关联管理者
    # @option options [Integer] :id 状态(可选)
    #
    # @return [Array] response, coupon
    #
    def add_print_count_by_one(options = {})
      response = ResponseStatus.__rescue__ do |res|
        manager, order_id, status = options[:manager], options[:id]

        order = Order.query_first_by_id(order_id)

        res.__raise__(ResponseStatus::Code::ERROR, '订单不存在') if order.blank?

        order.print_count = (order.print_count || 0) + 1
        order.save!
      end

      return response
    end

    # 管理者查询该学校的订单
    #
    # @param options [Hash]
    # @option options [Manager] :manager 关联管理者
    # @option options [Date] :date 日期(可选)
    # @option options [Status] :status 状态(可选)
    # @option options [Integer] :page 状态(可选)
    # @option options [Integer] :limit 状态(可选)
    #
    # @return [Array] response, coupon
    #
    def query_orders_for_management(options = {})
      orders = []

      catch_proc = proc{
        orders = []
      }

      response = ResponseStatus.__rescue__(catch_proc) do |res|

        manager, date, status = options[:manager], options[:date], options[:status]

        if date.present?
          date = Date.parse(date)
        else
          date = Time.now
        end
        res.__raise__(ResponseStatus::Code::ERROR, '参数错误') if manager.blank?

        res.__raise__(ResponseStatus::Code::ERROR, '您没有管辖校区') if manager.campus.blank?

        orders = self.query_by_options.includes(:order_items => {specification: :product}).joins(:payment).where('payments.id > 0 and orders.campus_id = ?', manager.campus.id).where('orders.created_at >= ? AND orders.created_at <= ?', date.beginning_of_day, date.end_of_day)

        if status.present?
          orders = orders.where(status: status)
        else
          orders = orders.where(status: Order::Status::PAYMENT_SUCCESS)
        end

        # 分页
        #orders = orders.page(options[:page]).per(options[:limit])

        # 排序
        orders = orders.order('orders.created_at desc')
      end

      return response, orders
    end
  end

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id            :integer          not null, primary key
#  store_id      :integer          not null
#  name          :string(255)      not null               # 商品名
#  logo_filename :string(255)      not null               # 商品logo缩略图
#  brief         :string(255)      default("暂无简介")        # 商品简介
#  min_price     :string(255)      default("0.0")         # 规格中最低价
#  max_price     :string(255)      default("0.0")         # 规格中最高价
#  status        :integer          default("1"), not null
#  pinyin        :string(255)                             # 拼音
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  month_sale    :integer          default("23")          # 月售
#  category_id   :integer                                 # 关联分类
#

class Product < ActiveRecord::Base

  belongs_to :store

  has_one :nutrition

  has_many :specifications

  has_many :product_images

  belongs_to :category

  # mixin 管理员查询商品
  include Concerns::Management::Api::V1::ProductConcern

  # 商铺logo挂载
  mount_uploader :logo_filename, ImageUploader

  # 删除后检查所在分类需不需要删除
  after_destroy :check_category_after_destroy

  # 更新分类
  after_save :check_category_save

  # 拼音
  before_save :set_pinyin, :set_default_brief

  module Status
    include Concerns::Dictionary::Module::I18n

    # 上架
    Normal = 1

    # 下架
    Pending = 2

    # 全部
    ALL = get_all_values
  end

  # after_destroy
  def check_category_after_destroy
    category = self.category
    if category.present? && category.products.count < 1
      category.destroy!
    end
  end

  # after_save
  def check_category_save
    if self.category_id_changed? && self.category_id_was.present?
      category = Category.query_first_by_id(self.category_id_was)
      if category.present? && category.products.count < 1
        category.destroy!
      end
    end
  end

  # 状态为Normal的规格
  def normal_specifications
    self.specifications.where(status: Specification::Status::Normal)
  end

  # 根据id获取商品详情
  def self.get_product_detail_by_id(params)
    response_status = ResponseStatus.default
    data = nil
    begin
      raise RestError::MissParameterError if params[:product_id].blank?
      data = Product.where(:id => params[:product_id]).includes(:specifications).references(:specifications).where('specifications.status = ?', Specification::Status::Normal)
      response_status = ResponseStatus.default_success
    rescue Exception => ex
      Rails.logger.error(ex.message)
      response_status.message = ex.message
    end

    return response_status, data
  end

  def self.search_product_for_api(params)
    response_status = ResponseStatus.default
    data = nil
    begin
      raise RestError::MissParameterError if params[:campus_id].blank? || params[:keyword].blank?
      data = self.search_product_by_keyword(params[:campus_id], params[:keyword])
      response_status = ResponseStatus.default_success
    rescue Exception => ex
      Rails.logger.error(ex.message)
      response_status.message = ex.message
    end

    return response_status, data
  end

  # 根据关键字模糊搜索指定学校里的商品
  def self.search_product_by_keyword(campus_id, keyword)
    keyword = "'%#{keyword.downcase}%'"
    self.includes(:store => :campuses).references(:campuses).where({campuses: {id: campus_id}}).where('products.status = ?', Product::Status::Normal).where("products.name like #{keyword} or products.pinyin like #{keyword}")
  end

  # 分类名称(快捷方法)
  def category_name
    self.category.try(:name)
  end

  # 设置拼音
  def set_pinyin
    if self.changed.include?('name')
      self.pinyin = Pinyin.t(self.name, splitter: '').downcase
    end
  end

  def set_default_brief
    self.brief ||= '暂无简介'
  end

  # def create_product(name, price, category, brief = '', ka = nil)
  #
  #   Product.transaction do
  #     pro = Product.new
  #     pro.name = name
  #     pro.brief = brief if brief.present?
  #     pro.category = category if category.present?
  #     pro.store = Store.first
  #     pro.logo_filename = 'null'
  #
  #     pro.save!
  #     spe = Specification.new
  #     spe.name = '规格'
  #     spe.value = '大'
  #     spe.price = price
  #     spe.product = pro
  #     spe.stock = 500
  #     spe.stock_per_day = 500
  #     spe.save!
  #
  #     if ka.present?
  #       nutrition = Nutrition.new
  #       nutrition.energy = ka
  #       nutrition.product = pro
  #       nutrition.save!
  #     end
  #   end
  #
  # end

end

app/controllers/management/api/application_controller.rb
class Management::Api::ApplicationController < ActionController::Base

  include Shared::Concerns::ApplicationControllerConcern

  before_filter :authorization_filter_for_management

  # 管理者不存在的错误
  class ManagerNotFoundError < StandardError

  end

  def authorization_filter_for_management
    token = request.headers['access-token']
    Rails.logger.error("access-token:#{token}")

    message= nil
    begin
      if token.blank?
        message = '缺少token参数'
      else
        phone = TsaoUtil.decode_jwt_user_session(token)
        if phone.present?
          puts "phone:#{phone}"
          manager = Manager.query_first_by_options({phone: phone})
          if manager.present?
            @manager = manager
            params[:manager] = @manager
          else
            raise ManagerNotFoundError
          end
        else
          raise ManagerNotFoundError
        end
      end
    rescue ManagerNotFoundError => err
      message = '没有权限'
    end
    if message.present?
      Rails.logger.error(message)

      render json: {status: ResponseStatus.need_login}, status: 200
    end

  end
end

app/controllers/management/api/v1/managers_controller.rb
class Management::Api::V1::ManagersController < Management::Api::ApplicationController

  # 跳过过滤器
  skip_before_action :authorization_filter_for_management, only: [:send_login_code, :login_with_sms_code]

  # 短信登陆
  def login_with_sms_code
    @response_status, @manager, @token = Manager.validate_login_with_sms_token(params)
  end

  # 发送登录短信
  def send_login_code
    @response_status, @token = Manager.send_sign_in_code(params)
  end

  # 自动登录
  def index
    @response_status = ResponseStatus.default_success
    @manager = params[:manager]
  end

end

app/controllers/management/api/v1/orders_controller.rb
class Management::Api::V1::OrdersController < Management::Api::ApplicationController

  # 获取订单列表
  def index
    @response_status, @orders = Order.query_orders_for_management(params)
  end

  def update
    @response_status = Order.add_print_count_by_one(params)
  end
end

app/controllers/management/management_base_controller.rb
class Management::ManagementBaseController < ActionController::Base

  include Shared::Concerns::ApplicationControllerConcern

  layout 'management'

  before_filter :authenticate_management_manager!

  before_filter :set_manager_in_params

  # before_render :detect_response_from_model_method

  # 在请求参数中加入manager
  def set_manager_in_params
    params[:manager] = current_management_manager
  end

  def is_management_controller?
    true
  end

  # 检查是否存在@response的message
  def render *args
    @response ||= nil
    if @response.present? && @response.message.present?
      flash[:alert] = @response.message
      Rails.logger.debug("----------@response报错:#{@response.message}")
      # 如果有重写返回地址,则直接跳转,不渲染了
      if self.respond_to?(:redirect_url_if_error)
        return  redirect_to self.redirect_url_if_error, flash: {alert: @response.message}
      else
        return  redirect_to request.referrer, flash: {alert: @response.message}
      end
    end
    super
  end

end

app/controllers/management/managers_controller.rb
class Management::ManagersController < Management::ManagementBaseController

  def show

  end

end

app/controllers/management/orders_controller.rb
class Management::OrdersController < Management::ManagementBaseController

  # 管理者获取自身校区的订单
  def index
    @response, @orders = Order.query_orders_for_management(params)
  end

end

app/controllers/management/products_controller.rb
class Management::ProductsController < Management::ManagementBaseController

  # 管理者获取商铺的商品列表
  def index
    @response, @store, @products = Product.query_store_products_for_management(params)
  end

  # 管理者查看商品详情
  def show
    @response, @store, @product = Product.query_product_for_management(params)
  end

  # 管理者更新商品详情
  def update
    @response, @store, @product = Product.create_or_update_product_for_management(params)
    if @response.is_successful?
      @response.message = '请刷新页面'
    end
  end

  # 管理者添加商品详情
  def create
    @response, @store, @product = Product.create_or_update_product_for_management(params)
  end

  def new
  end
end

app/controllers/management/statistics_controller.rb
class Management::StatisticsController < Management::ManagementBaseController

  # 管理者获取自身校区的店铺的商品统计
  def index
    @response, @stores_time_to_order_array, @campus = Campus.statistic_for_date(params)
  end

end

app/controllers/management/stores_controller.rb
class Management::StoresController < Management::ManagementBaseController

  # 管理者获取自身校区的订单
  def index
    @response, @stores = Store.query_for_management(params)
  end

  def show
    @response, @store = Store.query_detail_for_management(params)
  end

  def update
    @response, @store = Store.create_or_update_with_options(params)
  end

  def new

  end

  def create
    @response, @store = Store.create_or_update_with_options(params)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_filter :user_about
  def show
    @response_status, @product = Product.get_product_detail_by_id(params)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/management/products/_form.html.slim
= render 'management/common/left_nav'
.col.s8.m10.card ng-controller='ProductDetailController'
  .row.padding-horizontal.section
    - store =  @store || Store.new
    - product = @product || Product.new
    - url = action_new? ? management_store_products_path : management_store_product_path(store, product)

    - method = action_new? ? :post : :put
    = form_for product, url: url, class: %w(col s12), method: method do |f|
      .row
        .input-field.col.s6
          =f.text_field :name, placeholder: '', type: 'text', id: 'name'
          label for="name"  商品名称

        .input-field.col.s4
          .input-field.col.s12
            = select(:product, :status, Product::Status.get_all_values.collect {|status| [ Product::Status.get_desc_by_value(status), status ] })

            label 商品状态
        .input-field.col.s2
          .file-field.input-field
            .btn.store-logo-btn
              = f.file_field :logo_filename, id: 'logo_filename', onchange: 'readURL(this);'
          = qiniu_img_tag(product.logo_filename, ImageTag::ImgHelper::ImageStyle::Square_LOGO, class: 'store-logo-img')
      .row
        .input-field.col.s6
          input type='text' name='product[category]' id='category' placeholder='饮料' value='#{product.category_name}'
          label for="category"  分类
        .input-field.col.s6
          = f.text_field :brief, placeholder: '简介', type: 'text', id: 'brief'
          label for="brief"  简介
      .row
        .col.s12
          .card
            .card-content
              .product-images-scroller
                - product.product_images.each do |product_image|
                  .product-image-div  data-ng-mouseleave="hoverOut($event)" data-ng-mouseover='hoverIn($event)'
                    = qiniu_img_tag(product_image.image_name, ImageTag::ImgHelper::ImageStyle::Square_LOGO, {class: 'product-image'})
                    a.btn-floating.btn-large.waves-effect.waves-light.red.hover-btn ng-click='removeImage($event)'
                      |删
                      input.product-image-input type='text' name='product_image_ids[]' value="#{product_image.id}"
            .card-action
              .file-field.input-field#input_bar
                .btn
                  input type='file' onchange='readProductImagesURL(this);' name='new_images[]' 上传


      h5
        | 规格
        .row
          .col.s12
            .card
              .card-content style='min-height: 6em;'
                .row
                  .input-field.col.s4
                    input type='text' name='specification_name' id='specification_name' placeholder='颜色' value='#{product.specifications.try(:first).try(:name)}'
                    label for="specification_name"  规格



                .row
                  .col.s4
                    .btn.waves-effect.waves-light.btn-small ng-click='AddNewSpecificationRow()' 添加
                .row
                  #specification-container
                    - product.normal_specifications.each do |spe|
                      - random_row_id = "row-#{rand(36 ** 6).to_s(36)}"
                      - random_id_for_value = "a#{rand(36 ** 6).to_s(36)}"
                      - random_id_for_price = "b#{rand(36 ** 6).to_s(36)}"
                      - random_id_for_stock = "c#{rand(36 ** 6).to_s(36)}"
                      - random_id_for_cost = "d#{rand(36 ** 6).to_s(36)}"
                      .row id='#{random_row_id}'
                        .input-field.col.s2
                          input type='text' name='specification_values[]' placeholder='红' id='#{random_id_for_value}' value='#{spe.value}'
                          label for='#{random_id_for_value}'  规格
                        .input-field.col.s2
                          input type='text' name='specification_prices[]' placeholder='3.5' id='#{random_id_for_price}' value='#{spe.price}'
                          label for='#{random_id_for_price}'  价格
                        .input-field.col.s2
                          input type='text' name='specification_costs[]' placeholder='3.5' id='#{random_id_for_cost}' value='#{spe.cost}'
                          label for='#{random_id_for_cost}'  成本价
                        .input-field.col.s2
                          input type='text' name='specification_stocks[]' placeholder='100' id='#{random_id_for_stock}' value='#{spe.stock}'
                          label for='#{random_id_for_stock}'  库存
                        .col.s4
                          a.btn-floating.btn-large.waves-effect.waves-light.red.hover-btn ng-click='RemoveSpecification("#{random_row_id}")'
                            |删
      .row.center-align
        .col.s12
          button.waves-effect.waves-light.btn type='submit'  提交
javascript:
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('.store-logo-img')
                .attr('src', e.target.result);
      };

      reader.readAsDataURL(input.files[0]);
    }
  }

  function readProductImagesURL(input) {
    if (input.files && input.files[0]) {
      _.forEach(input.files, function(file, index){
        var reader = new FileReader();

        var product_image_div = $('<div class="product-image-div" data-ng-mouseleave="hoverOut($event)" data-ng-mouseover="hoverIn($event)"> <img class="product-image"> <a class="btn-floating btn-large waves-effect waves-light red hover-btn" ng-click="removeImage($event)" style="height:0px;" > 删 </a></div>');

        $('.product-images-scroller').append(product_image_div)

        reader.onload = function (e) {
          product_image_div.find('.product-image').attr('src', e.target.result);
        };

        reader.readAsDataURL(input.files[index]);

        // 隐藏input 创建新input
        var new_input = $('<div class="btn"> <input multiple="true" name="new_images[]" onchange="readProductImagesURL(this);" type="file">上传 </div>')
        $(input).parent().hide();

        $('#input_bar').append(new_input)
      });

    }
  }

app/views/management/products/create.html.slim
= render 'management/products/form'

app/views/management/products/index.html.slim
= render 'management/common/left_nav'
.col.s8.m10.card ng-controller='ProductStatisticController'
  .row
    .col.s2.push-s10
      a.waves-effect.waves-light.btn.narrow-btn href="#{new_management_store_product_path}"
        | 添加商品

  = form_tag management_store_products_path(@store), method: :get
    .row
      .input-field.col.s2
        select name='category_id'
          - @store.categories.each do |category|
            option[value="#{category.id}" selected=('selected' if category.name == params[:category_id])] =category.name
        label 分类
      .input-field.col.s2
        select name='status'
          - Product::Status::ALL.each do |status|
            option[value="#{status}" selected=('selected' if status == params[:status])]  = Product::Status.get_desc_by_value(status)
        label 状态
      .input-field.col.s3.push-s5
        button.waves-effect.waves-light.btn type='submit'
          i.material-icons.right search
          | 过滤

    .row
      table.striped
        thead
          tr
            th data-field="logo_filename"
            th data-field="name"  名称
            th data-field="category"  类别
            th data-field="status"  状态

        tbody
          -@products.each do |product|
            tr
              td
                = qiniu_img_tag(product.logo_filename, ImageTag::ImgHelper::ImageStyle::Square_LOGO)
              td
                =link_to product.name, management_store_product_path(@store, product)
              td = product.category_name
              td = Product::Status.get_desc_by_value product.status
    .row
      .col.s12.center-align
        = paginate @products

app/views/management/products/new.html.slim
= render 'management/products/form'

app/views/management/products/show.html.slim
= render 'management/products/form'

app/views/management/products/update.html.slim
= render 'management/products/form'